version: "3.8"

services:
  backend:
    image: node_boilerplate-server
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./:/usr/src/node_boilerplate
      - /usr/src/node_boilerplate/node_modules
    env_file:
      - ./.env
    depends_on:
      - mongodb
    networks:
      - node_boilerplate-internal

  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - data:/data/db
    networks:
      - node_boilerplate-internal

networks:
  node_boilerplate-internal:

volumes:
  data:
