#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

cd "$(dirname -- "$0")/.." || exit 1

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
nvm use --silent 2>/dev/null || true

npx commitlint --edit "$1"
